export const constants = {
  name: "Muhammad Rayan Shahid",
  handle: "RayanAIX",
  title: "Independent AI Researcher",
  age: 16,
  location: "Karachi, Pakistan",
  organization: "ByteBrilliance AI",
  tagline: "Building AI that measures how humans think — not just whether they're right.",
  email: "m.rayanshahid5@gmail.com",
  social: {
    github: "https://github.com/RayanAIX",
    linkedin: "https://linkedin.com/in/muhammadrayanshahid",
    kaggle: "https://kaggle.com/muhammadrayanshahid",
    huggingface: "https://huggingface.co/RayNetic",
    youtube: "https://youtube.com/@ByteBrillianceAI",
    substack: "https://substack.com/@muhammedrayanshahid",
  },
  doi: "10.5281/zenodo.18269740",
  doiUrl: "https://zenodo.org/records/18269740",
  repoUrl: "https://github.com/RayanAIX/HCMS-Human-Cognition-Measurement-System",
};
